# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestetodasastelas():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testetodasastelas(self):
    # Test name: teste todas as telas
    # Step # | name | target | value
    # 1 | open | /login-admin | 
    self.driver.get("https://sw-gestao-competencias-dw.vercel.app/login-admin")
    # 2 | setWindowSize | 1307x1040 | 
    self.driver.set_window_size(1307, 1040)
    # 3 | click | css=.col-md-5 > .row:nth-child(2) .form-control | 
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-5 > .row:nth-child(2) .form-control").click()
    # 4 | type | css=.col-md-5 > .row:nth-child(2) .form-control | teste1
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-5 > .row:nth-child(2) .form-control").send_keys("teste1")
    # 5 | click | css=.col-md-5 > .row:nth-child(3) .form-control | 
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-5 > .row:nth-child(3) .form-control").click()
    # 6 | type | css=.col-md-5 > .row:nth-child(3) .form-control | 123456
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-5 > .row:nth-child(3) .form-control").send_keys("123456")
    # 7 | click | linkText=Conectar | 
    self.driver.find_element(By.LINK_TEXT, "Conectar").click()
    # 8 | click | css=li:nth-child(2) p | 
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(2) p").click()
    # 9 | click | css=li:nth-child(3) p | 
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(3) p").click()
    # 10 | click | linkText=Leds Skills | 
    self.driver.find_element(By.LINK_TEXT, "Leds Skills").click()
    # 11 | click | css=li:nth-child(3) p | 
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(3) p").click()
    # 12 | click | linkText=IaM Here | 
    self.driver.find_element(By.LINK_TEXT, "IaM Here").click()
    # 13 | click | css=li:nth-child(3) p | 
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(3) p").click()
    # 14 | click | css=li:nth-child(4) p | 
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(4) p").click()
    # 15 | click | css=.col-md-6 .form-control | 
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-6 .form-control").click()
    # 16 | type | css=.col-md-6 .form-control | stonebi
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-6 .form-control").send_keys("stonebi")
    # 17 | click | css=.col-md-3:nth-child(2) .form-control | 
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-3:nth-child(2) .form-control").click()
    # 18 | type | css=.col-md-3:nth-child(2) .form-control | 0002-01-01
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-3:nth-child(2) .form-control").send_keys("0002-01-01")
    # 19 | type | css=.col-md-3:nth-child(2) .form-control | 0020-01-01
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-3:nth-child(2) .form-control").send_keys("0020-01-01")
    # 20 | type | css=.col-md-3:nth-child(2) .form-control | 0202-01-01
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-3:nth-child(2) .form-control").send_keys("0202-01-01")
    # 21 | type | css=.col-md-3:nth-child(2) .form-control | 2020-01-01
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-3:nth-child(2) .form-control").send_keys("2020-01-01")
    # 22 | click | css=.col-md-3:nth-child(3) .form-control | 
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-3:nth-child(3) .form-control").click()
    # 23 | type | css=.col-md-3:nth-child(3) .form-control | 0002-12-31
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-3:nth-child(3) .form-control").send_keys("0002-12-31")
    # 24 | type | css=.col-md-3:nth-child(3) .form-control | 0020-12-31
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-3:nth-child(3) .form-control").send_keys("0020-12-31")
    # 25 | type | css=.col-md-3:nth-child(3) .form-control | 0202-12-31
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-3:nth-child(3) .form-control").send_keys("0202-12-31")
    # 26 | type | css=.col-md-3:nth-child(3) .form-control | 2020-12-31
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-3:nth-child(3) .form-control").send_keys("2020-12-31")
    # 27 | click | css=.row:nth-child(2) .form-control | 
    self.driver.find_element(By.CSS_SELECTOR, ".row:nth-child(2) .form-control").click()
    # 28 | type | css=.row:nth-child(2) .form-control | fulano,ciclano,beltrano
    self.driver.find_element(By.CSS_SELECTOR, ".row:nth-child(2) .form-control").send_keys("fulano,ciclano,beltrano")
    # 29 | click | id=formControlsTextarea | 
    self.driver.find_element(By.ID, "formControlsTextarea").click()
    # 30 | type | id=formControlsTextarea | Sobre: projeto sobre criacao de banco de dados. teste usando sellenium\n\n\nObjetivo:
    self.driver.find_element(By.ID, "formControlsTextarea").send_keys("Sobre: projeto sobre criacao de banco de dados. teste usando sellenium\\n\\n\\nObjetivo:")
    # 31 | click | css=.btn-fill | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-fill").click()
    # 32 | click | css=li:nth-child(5) p | 
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(5) p").click()
    # 33 | click | id=basic-nav-dropdown | 
    self.driver.find_element(By.ID, "basic-nav-dropdown").click()
    # 34 | click | linkText=ToDoDay | 
    self.driver.find_element(By.LINK_TEXT, "ToDoDay").click()
  
